name: borsh
version: 0.1.0
repository: https://github.com/cryptoplease/borsh
description: >-
  Implementation of the borsh serialization scheme

environment:
  sdk: '>=2.13.0 <3.0.0'

dev_dependencies:
  build_runner: ^2.0.6
  mews_pedantic: ^0.2.1
  test: ^1.17.10
dependencies: 
  source_gen: ^1.0.3
